//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammeEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DISTRI_DEVEntities : DbContext
    {
        public DISTRI_DEVEntities()
            : base("name=DISTRI_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ART_Article> ART_Article { get; set; }
        public virtual DbSet<ART_CouleurType> ART_CouleurType { get; set; }
        public virtual DbSet<ART_Famille> ART_Famille { get; set; }
        public virtual DbSet<ART_Grille> ART_Grille { get; set; }
        public virtual DbSet<ART_Rayon> ART_Rayon { get; set; }
        public virtual DbSet<PAR_Photo> PAR_Photo { get; set; }
        public virtual DbSet<TRF_Tarif> TRF_Tarif { get; set; }
        public virtual DbSet<ART_Couleur> ART_Couleur { get; set; }
    }
}
