//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammeEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR_Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAR_Photo()
        {
            this.PAR_Photo1 = new HashSet<PAR_Photo>();
        }
    
        public int ID { get; set; }
        public int ID_PhotoType { get; set; }
        public int ID_Objet { get; set; }
        public int ID_ObjetType { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string Filename { get; set; }
        public int ID_DernierUtilisateur { get; set; }
        public System.DateTime DateCreation { get; set; }
        public Nullable<System.DateTime> DateModification { get; set; }
        public Nullable<int> RowVersion { get; set; }
        public Nullable<int> ID_PhotoLie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAR_Photo> PAR_Photo1 { get; set; }
        public virtual PAR_Photo PAR_Photo2 { get; set; }
    }
}
